# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='keywords',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
