# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_customer_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('upload', models.FileField(upload_to=b'')),
            ],
        ),
    ]
