# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='title',
        ),
    ]
